pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Hello"
    echo "World!"

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world from the task assistant!'